import Head from 'next/head'
//import ArticleList from '../components'
import styles from '../styles/Layout.module.css'
import homeStyles from '../styles/Home.module.css'

export default function Home({articles}) {
  return (
    // <div>
    //   <Head>
    //     <title>Seth Frank</title>
    //   </Head>
    //   <h1>Hello! My name is Seth Frank</h1>

    //   <ArticleList articles={articles} />
    // </div>




    <div className={styles.container}>
      <Head>
        <title>Seth Frank</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello! I'm Seth Frank
        </h1>

        <div className={homeStyles.homePicGrid}>
          <div className={homeStyles.homePic}>
            <p className={styles.description}>I am currently a first-year student at Worcester Polytechnic Institute pursuing a Bachelor's degree in Computer Science. Check out more about my work and passions.</p>
          </div>
          <div className={homeStyles.homePic}>
            <img src="seth.jpg"></img>
          </div>          
        </div>

        <div class={homeStyles.hl} />

        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Learn more about interests and passions.</p>
          </a>

          <a href="/resume" className={styles.card}>
            <h2>Resume &rarr;</h2>
            <p>View and download my resume.</p>
          </a>

          <a
            href="/academics"
            className={styles.card}
          >
            <h2>Academics &rarr;</h2>
            <p>Learn more about my studies at Worcester Polytechnic Institute.</p>
          </a>

          <a
            href="/contact"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>Reach out to me for further inquiries.</p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)
  const articles = await res.json()

  return {
    props: {
      articles
    }
  }
}
